# Generated by Django 5.0.6 on 2024-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_company_remove_profile_company_user_company_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
