# Generated by Django 5.0.6 on 2024-06-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_invoice_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.AddField(
            model_name="company",
            name="defaultRate",
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["order", "invoice"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="item",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
