services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    volumes:
      - ../:/app
    build:
      target: testing
    command:
      [
        'pdm',
        'run',
        'manage.py',
        'runserver',
        '0.0.0.0:8000'
      ]

  database:
    extends:
      file: docker-compose.yml
      service: database
