name: abbs
services:
  web:
    build:
      context: ..
      dockerfile: dockerfiles/abbs/Dockerfile
      target: production
    command: [ 'gunicorn','abbs.wsgi','-b 0.0.0.0:8000' ]
    depends_on:
      - database
    env_file:
      - ../.env
    volumes:
      - static:/app/staticfiles/
    expose:
      - 8000

  database:
    image: postgres
    env_file:
      - ../.env
    expose:
      - 5432

  server:
    build:
      context: ..
      dockerfile: dockerfiles/nginx/Dockerfile
    ports:
      - 80:80
      # - 443:443 #HTTPs ports
    volumes:
      - static:/staticfiles/
    depends_on:
      - web

volumes:
  static:
